behaviors:
  MemoryAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      num_layers: 3
      hidden_units: 256
      normalize: true
      memory:
        memory_size: 256
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.8
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 200000000
    time_horizon: 64
    summary_freq: 5000





environment_parameters:
  timerNeededToSee:
    curriculum:
      - name: FindLesson01 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 18
        value: 0.1  
      - name: FindLesson02 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 18
        value: 0.2  
      - name: FindLesson03 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 18
        value: 0.3  
      - name: FindLesson04
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 23
        value: 0.5  
      - name: FindLesson05
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 27.5
        value: 0.75 
      - name: FindLesson06
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 30
        value: 1 
      - name: FindLesson07
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 32.5
        value: 1.25 
      - name: FindLesson08
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 35
        value: 1.5
      - name: FindLesson09 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 40
        value: 2
      - name: FindLesson10
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 45
        value: 2.5
      - name: FindLesson011
        value: 3
  obstacles:
    curriculum:
      - name: FindLesson01 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 18
        value: 0  
      - name: FindLesson02 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 18
        value: 0  
      - name: FindLesson03 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 18
        value: 0  
      - name: FindLesson04
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 23
        value: 10  
      - name: FindLesson05
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 27.5
        value: 10 
      - name: FindLesson06
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 30
        value: 10
      - name: FindLesson07
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 32.5
        value: 10 
      - name: FindLesson08
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 35
        value: 20
      - name: FindLesson09 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 40
        value: 20
      - name: FindLesson10
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 45
        value: 30
      - name: FindLesson011
        value: 30






# environment_parameters:
#   staticEnemies:
#     curriculum:
#       - name: FindLesson01 
#         completion_criteria: 
#           measure: reward
#           behavior: MemoryAgent   
#           signal_smoothing: true
#           min_lesson_length: 100
#           threshold: 110
#         value: 30  
#       - name: FindLesson02 
#         completion_criteria: 
#           measure: reward
#           behavior: MemoryAgent   
#           signal_smoothing: true
#           min_lesson_length: 100
#           threshold: 60
#         value: 20   
#       - name: FindLesson03 
#         value: 5 
#   movingEnemies:
#     curriculum:
#       - name: FindLesson01 
#         completion_criteria: 
#           measure: reward
#           behavior: MemoryAgent   
#           signal_smoothing: true
#           min_lesson_length: 100
#           threshold: 110
#         value: 3     
#       - name: FindLesson02 
#         completion_criteria: 
#           measure: reward
#           behavior: MemoryAgent   
#           signal_smoothing: true
#           min_lesson_length: 100
#           threshold: 60
#         value: 5   
#       - name: FindLesson03 
#         value: 5