behaviors:
  MemoryAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      num_layers: 3
      hidden_units: 256
      normalize: true
      memory:
        memory_size: 256
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.8
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 200000000
    time_horizon: 64
    summary_freq: 5000



environment_parameters:
  goals:
    curriculum:
      - name: MoveLesson00 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 100
        value: 500
      - name: MoveLesson01 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 50
        value: 250
      - name: MoveLesson02 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 30
        value: 100
      - name: MoveLesson03 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 30
        value: 75        
      - name: MoveLesson04 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 20
        value: 50    
      - name: MoveLesson05 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 11
        value: 25
      - name: MoveLesson06 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 6.5
        value: 15  
      - name: MoveLesson07
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4.5
        value: 10 
      - name: MoveLesson08
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.5
        value: 5  
      