behaviors:
  MemoryAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      num_layers: 3
      hidden_units: 256
      normalize: true
      memory:
        memory_size: 256
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.8
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 200000000
    time_horizon: 64
    summary_freq: 5000



environment_parameters:
  obstacles:
    curriculum:
      - name: exploreLesson00 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 4
        value: 0  
      - name: exploreLesson01 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 4
        value: 10        
      - name: exploreLesson02 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4
        value: 20    
      - name: exploreLesson03 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4
        value: 30  
      - name: exploreLesson04 
        completion_criteria: 
          measure: reward
          behavior: MemoryAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4
        value: 40  


      