behaviors:
  ResNetAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      vis_encode_type: resnet
      num_layers: 2
      hidden_units: 128
      normalize: true
      memory:
        memory_size: 256
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 1
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 200000000
    time_horizon: 64
    summary_freq: 5000

environment_parameters:
  turrets:
    curriculum:
      - name: dodgeLesson01 # This is the start of dodge lesson
        completion_criteria: 
          measure: reward
          behavior: ResNetAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2
        value: 1  
      - name: dodgeLesson02 
        completion_criteria: 
          measure: reward
          behavior: ResNetAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4
        value: 2 
      - name: dodgeLesson03 
        completion_criteria: 
          measure: reward
          behavior: ResNetAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 6
        value: 3 
      - name: dodgeLesson04
        completion_criteria: 
          measure: reward
          behavior: ResNetAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 8
        value: 4 
      - name: dodgeLesson05
        completion_criteria: 
          measure: reward
          behavior: ResNetAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 10
        value: 5 
  obstacles:
      curriculum:
      - name: dodgeLesson01 # This is the start of dodge lesson
        completion_criteria: 
          measure: reward
          behavior: ResNetAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2
        value: 0
      - name: dodgeLesson02 
        completion_criteria: 
          measure: reward
          behavior: ResNetAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 4
        value: 0
      - name: dodgeLesson03 
        completion_criteria: 
          measure: reward
          behavior: ResNetAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 6
        value: 10
      - name: dodgeLesson04
        completion_criteria: 
          measure: reward
          behavior: ResNetAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 8
        value: 20
      - name: dodgeLesson05
        completion_criteria: 
          measure: reward
          behavior: ResNetAgent   
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 10
        value: 20